version: '3'
services:
  app:
    container_name: app
    build: ./nodejs
    entrypoint: wait-for db:3306 -t 40 -- ./start.sh
    volumes:
      - ./nodejs/:/app
    depends_on:
      - db
  db:
    container_name: db
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    tty: true
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
    volumes:
      - ./mysql:/var/lib/mysql
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 8080:80
    depends_on:
      - app
